-- 코드를 입력하세요
SELECT A.FLAVOR
FROM 
    (SELECT FLAVOR
    FROM FIRST_HALF 
    WHERE TOTAL_ORDER > 3000 
    ORDER BY TOTAL_ORDER DESC) A,
    ICECREAM_INFO I
WHERE A.FLAVOR = I.FLAVOR AND I.INGREDIENT_TYPE = "fruit_based"
;