WITH VW_JOIN_TABLE AS (
SELECT A.USER_ID AS USER_ID_A
     , B.USER_ID AS USER_ID_B
     , SALES_DATE
  FROM USER_INFO A
     , ONLINE_SALE B
 WHERE A.USER_ID = B.USER_ID(+)
   AND TO_CHAR(JOINED, 'YYYY') = '2021'
),
VW_JOIN_CNT AS (
SELECT COUNT(COUNT(USER_ID_A)) AS CNT
  FROM VW_JOIN_TABLE
 GROUP BY USER_ID_A
)
SELECT 
       SUBSTRB(YYYYMM, 1, 4) AS YEAR
     , TO_NUMBER(SUBSTRB(YYYYMM, 5, 2)) AS MONTH
     , COUNT(USER_ID_B) AS PURCHASED_USERS
     , ROUND(COUNT(USER_ID_B) / (SELECT CNT FROM VW_JOIN_CNT), 1) AS PUCHASED_RATIO
  FROM (
        SELECT TO_CHAR(SALES_DATE, 'YYYYMM') AS YYYYMM
             , USER_ID_B
          FROM VW_JOIN_TABLE
         WHERE USER_ID_B IS NOT NULL
         GROUP BY TO_CHAR(SALES_DATE, 'YYYYMM'), USER_ID_B
       )
 GROUP BY SUBSTRB(YYYYMM, 1, 4), SUBSTRB(YYYYMM, 5, 2)
 ORDER BY YEAR ASC, MONTH ASC
;