-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
from BOOK join BOOK_SALES on BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE like "2022-01%"
group by CATEGORY, DATE_FORMAT(SALES_DATE,"%Y-%m")
order by CATEGORY
;