SELECT DISTINCT
       ID
     , EMAIL
     , FIRST_NAME
     , LAST_NAME
  FROM DEVELOPERS A
     , SKILLCODES B
 WHERE SUBSTR(REVERSE(CONV(SKILL_CODE, 10, 2)), INSTR(REVERSE(CONV(CODE, 10, 2)), '1') , 1) = '1'
   AND CATEGORY = 'Front End'
 ORDER BY ID ASC
;